### ISSUE TITLE
Reliable code motion

### ISSUE THREAD

**Issue by emilaxelsson** [Feldspar/feldspar-language#135]
## Proposal

On the branch [code-motion3](../tree/code-motion3) I've made a version of the old `codeMotion` that I think is reliable and optimal (but still as inefficient as the old `codeMotion`).

Due to problems with `codeMotion` and `codeMotion2` (see below), I suggest that we use this one as the default implementation and hide the other ones behind options.

(In the end, we have to make an implementation that is both reliable and efficient, but hopefully this will do for now.)

## Problematic case 1

We know that there are cases where the old code motion (`codeMotion`) misses opportunities for sharing. As far as I understand, the new implementation (`codeMotion2`) fixes many of these cases, but today, Anders found a case where both implementations miss opportunities, but still `codeMotion` does a much better job than `codeMotion2`.

The example is

~~~~{.haskell}
concatV :: Pull DIM1 (Pull1 IntN) -> DPush DIM1 IntN
concatV xs = fromZero $ fold (++) empty xs
~~~~

on the current `internal_shape` branch 06c7b752b82cce9b45a963572fdec84413a615af.

## Problematic case 2

Another interesting example is:

~~~~{.haskell}
sharing :: Data Index -> Data Index
sharing x = (a+b+c) + (a+b) + (a+b+c)
  where
    a = x*3
    b = x*5
    c = x*7
~~~~

This is a typical example where `codeMotion` misses sharing, because it shares `a+b+c` first, and then it doesn't discover that `a+b` can be shared between the lifted term and the thing that is left after lifting. One solution to this problem is to iterate `codeMotion`, but the problem with that is the the old implementation often doesn't reach a fixed point. This is because it thinks that hoisting outside of a lambda is *always* a good thing. However, this is only true for lambdas that will be reduced multiple times. But we have quite a lot of *one-shot* lambdas in our programs. Most notably, the lambda in a let binding is one-shot. So `codeMotion` thinks that it's good to hoist outside of let bindings, and this easily leads to a situation where independent bindings are hoisted outside of each other on each iteration of `codeMotion`.

`codeMotion2` doesn't do a good job on the above example either. It creates bindings for *all* sub-expressions (except variables and constants), which is too many. (Of course this can be fixed by inlining afterwards, but I don't think it's a conscious decision for `codeMotion2` to behave in this way.)

## `codeMotion3`

`codeMotion3` is based on `codeMotion`, but it does not hoist over one-shot lambdas, so it can be iterated without problems with termination. Therefore, I think it's both reliable and optimal.

**Comment by emilaxelsson** [comment]
@jankner

**Comment by pjonsson** [comment]
What happens if you have a many-shot lambda that looks like this: `\x -> let x1 = .. x ... in let x2 = 3 in (x2*x1, let y = EXPENSIVE in (y, y))`?

I spent some time reading up on CSE/Code motion before we visited you. Talking about optimal in the context of CSE/code motion is dangerous because it doesn't coincide with our intuitive notion of optimal. Andreas Krall or one of the members of his group has a paper from the mid-90's which improves on optimal.

We take care of the extra bindings in the middle-end. The show-instance for that expression language is not completely precedence-aware but for debugging purposes you can usually make sense of the output from `printExpr2`.

`codeMotion2` currently does the job for us which saved us a bunch of time compared to implementing a new CSE and code motion pass. I don't feel strongly about this issue as long as the current code path continues to work. The patch to enable `codeMotion3` seems bogus, the new code is `| True = cm1 RET | True = cm2 RET | True = cm3` prepended above the old code path. Remove `CSE` from `defaultOptions` and you should hit the `| otherwise = cm1` case. If your patch is a strict improvement to `cm1` you can just replace that with `cm3`.

**Comment by emilaxelsson** [comment]
> What happens if you have a many-shot lambda that looks like this: \x -> let x1 = .. x ... in let x2 = 3 in (x2*x1, let y = EXPENSIVE in (y, y))?

I assume that those are Feldspar `let`s (i.e. `share`)? Which variables occur in `EXPENSIVE` (there has to be some variables in there for it to be expensive)?

(I'm not sure what you're after, so if this is an important question perhaps you could clarify.)

> I spent some time reading up on CSE/Code motion before we visited you. Talking about optimal in the context of CSE/code motion is dangerous because it doesn't coincide with our intuitive notion of optimal. Andreas Krall or one of the members of his group has a paper from the mid-90's which improves on optimal.

Granted. What I meant was that it produces an expression with the following properties:

  * No sharable (i.e. duplicated or hoistable) sub-expressions left
  * No unnecessary bindings (i.e. let bindings that are only used once) unless they were there from the start

(Modulo bugs, of course.)

> We take care of the extra bindings in the middle-end.

Yes, but I still think we need `codeMotion` to behave reliably. If we say that it's part of the specification of `codeMotion` to produce extra bindings and have a good reason to do so, then that's fine.

> The patch to enable codeMotion3 seems bogus

Yes, that was just for testing. I'll do as you suggest.

**Comment by emilaxelsson** [comment]
I should also say that the reason why I made `codeMotion3` instead of fixing `codeMotion2` is that I'm not familiar with the code of `codeMotion2`. I want to put my effort on the new implementation of the core language, in which I hope to make things right from the beginning.

**Comment by emilaxelsson** [comment]
I've merged in the changes 6433e11b72b89efc1f242e83fcc8939f544c96c3.

I left `cm1` in the `SICS` case in order not to break anything. Peter, can you check if `cm1` can be changed to `cm3`? If so, `cm3` can be moved to Syntactic. (But I think wait with moving until it becomes necessary.)

**Comment by pjonsson** [comment]
<blockquote><blockquote>What happens if you have a many-shot lambda that looks like this: \x -> let x1 = .. x ... in let x2 = 3 in (x2*x1, let y = EXPENSIVE in (y, y))?</blockquote>
I assume that those are Feldspar lets (i.e. share)? Which variables occur in EXPENSIVE (there has to be some variables in there for it to be expensive)?

(I'm not sure what you're after, so if this is an important question perhaps you could clarify.)</blockquote>

My question is whether EXPENSIVE will be maximally hoisted so it ends up outside of the outermost lambda or if the one-shot lambdas from the lets will prevent the floating.

**Comment by emilaxelsson** [comment]
Aha, yes, it will be maximally hoisted. The `choose` function that looks for a sub-expression to hoist sets a flag when it looks under a multi-shot lambda. If it goes under a one-shot lambda, the flag is just inherited from above, so one-shot lambdas don't prevent hoisting.

**Comment by pjonsson** [comment]
I don't see any commits to feldspar-compiler. Does `cabal test` in feldspar-compiler still pass?

**Comment by emwap** [comment]
Working on it.

**Comment by emilaxelsson** [comment]
Anders' last commit fixed the compiler. (I haven't been able to run the compiler for a while due to linking errors.)
